# Generated by Django 3.2.5 on 2021-07-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210725_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default='This is test description', max_length=1000),
            preserve_default=False,
        ),
    ]
