# Generated by Django 3.2.5 on 2021-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('RGTR', 'Registered'), ('INPR', 'In Progress'), ('DONE', 'Order ready'), ('CNLD', 'Order canceled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_order',
            field=models.CharField(choices=[('RPIR', 'Repair'), ('SRVS', 'Service'), ('CNST', 'Consultation'), ('WRNT', 'Warranty')], max_length=20),
        ),
    ]
