# Generated by Django 3.2.5 on 2021-07-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='position',
            field=models.CharField(choices=[('MNGR', 'Manager'), ('ENGN', 'Engineer'), ('TECH', 'Technician'), ('OPRT', 'Operator')], default='def', max_length=20),
            preserve_default=False,
        ),
    ]
