# Generated by Django 3.2.5 on 2021-07-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_employer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notifications',
            field=models.CharField(choices=[('MAIL', 'Email'), ('PHON', 'SMS'), ('TLGR', 'Telegram'), ('NONE', 'NO notifications')], default='test', max_length=20),
            preserve_default=False,
        ),
    ]
