# Generated by Django 3.2.5 on 2021-07-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_customer_order_customers_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customers_phone',
            new_name='customer',
        ),
    ]
